<?php

namespace Mhhetier\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticles() {
        $qb = $this->createQueryBuilder("a")
                              ->leftJoin("a.image","i")
                              ->addSelect("i")
                              ->leftJoin("a.categories","c")
                              ->addSelect("c")    
                              ->where ("a.publication = :val")
                              ->setParameter("val", 1)
                              ->orderBy("a.datecreation", "DESC");
        $query = $qb->getQuery();
        return $query->getResult();
    }
    
    public function getArticleById($id) {
        $qb = $this->createQueryBuilder("a")
                              ->leftJoin("a.image","i")
                              ->addSelect("i")
                              ->leftJoin("a.categories","c")
                              ->addSelect("c")    
                              ->where ("a.publication = 1 AND a.id = :val")
                              ->setParameter("val", $id);
        $query = $qb->getQuery();
        return $query->getOneOrNullResult();
    }
        
}
