<?php

namespace Mhhetier\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * imageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
}
